[2025-03-19T07:15:59.007+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-19T07:15:59.026+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: github_etl.load manual__2025-03-19T07:15:36.954180+00:00 [queued]>
[2025-03-19T07:15:59.031+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: github_etl.load manual__2025-03-19T07:15:36.954180+00:00 [queued]>
[2025-03-19T07:15:59.032+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-03-19T07:15:59.042+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2025-03-19 07:15:36.954180+00:00
[2025-03-19T07:15:59.045+0000] {standard_task_runner.py:63} INFO - Started process 561 to run task
[2025-03-19T07:15:59.047+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'github_etl', 'load', 'manual__2025-03-19T07:15:36.954180+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/github_etl.py', '--cfg-path', '/tmp/tmp4eyzjti_']
[2025-03-19T07:15:59.050+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask load
[2025-03-19T07:15:59.089+0000] {task_command.py:426} INFO - Running <TaskInstance: github_etl.load manual__2025-03-19T07:15:36.954180+00:00 [running]> on host cc427449653e
[2025-03-19T07:15:59.223+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='github_etl' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T07:15:36.954180+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T07:15:36.954180+00:00'
[2025-03-19T07:15:59.225+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-19T07:15:59.234+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-19T07:15:59.235+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/github_etl.py", line 444, in load
    df = pd.read_json(TRANSFORMED_FILE, lines=True)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 733, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 818, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/json/_json.py", line 858, in _get_data_from_filepath
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
IsADirectoryError: [Errno 21] Is a directory: '/opt/airflow/dags/data/transformed.json'
[2025-03-19T07:15:59.244+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=github_etl, task_id=load, run_id=manual__2025-03-19T07:15:36.954180+00:00, execution_date=20250319T071536, start_date=20250319T071559, end_date=20250319T071559
[2025-03-19T07:15:59.262+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 20 for task load ([Errno 21] Is a directory: '/opt/airflow/dags/data/transformed.json'; 561)
[2025-03-19T07:15:59.309+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-19T07:15:59.319+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T07:15:59.323+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
